name: 01-1. GitHub Actions Demo
on: 
  workflow_dispatch:
  workflow_call:
  push:
    branches:
      - main
    paths:
      - 'labs/**'
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - run: echo "This job auto triggered by ${{ github.event_name }} event."
      - run: echo "This job runs on ${{ runner.os }} server hosted by GitHub!"
      - run: echo "The name of your branch is ${{ github.ref }}."
      - run: echo "The repository is ${{ github.repository }}."
      - name: Check out repository code
        uses: actions/checkout@v3
      - run: echo "${{ github.repository }} repository is cloned to runner."
      - run: echo "The workflow is now ready to test your code on runner."
      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}
      - run: echo "ðŸ This job's status is ${{ job.status }}."
      - name: Adding markdown
        run: echo "### Hello world! :rocket:" >> "$GITHUB_STEP_SUMMARY"
      - name: Hello world
        uses: actions/hello-world-javascript-action@v1
        with:
          who-to-greet: "Mona the Octocat"
        id: hello
      - name: Echo the greeting's time
        run: echo 'The time was ${{ steps.hello.outputs.time }}.'  